version: '3.4'

services:
  video_encoder:
    build:  
      context: ./video_encoder
    depends_on: 
      - minio
    volumes:
      - ./video_encoder:/home/api 
      - ./data/videos_store:/home/videos_store 
    env_file: 
       - .env
    ports:
      - "${ENCODER_PORT}:${ENCODER_PORT}"
    #restart: unless-stopped
    networks: 
      - backend
    working_dir: /go/src/api
    command: bash -c "go run main.go"
    container_name: myyt-encoder

  #service for yt api
  api:
    build:
      context: ./api
    volumes:
        - ./api:/go/src/api 

    env_file: 
       - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on: 
      - msql
      - minio
      - smtp
    networks: 
      - backend
      - frontend
    command: bash -c "go run main.go"
    container_name: ${API_CONTAINER}

  #service for database
  msql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "${MYSQL_PORT}:3306"    
    networks: 
       - backend
       - search
    volumes: 
      - ./data/mysql:/var/lib/mysql
    container_name: ${MYSQL_CONTAINER}
    hostname: ${MYSQL_HOST}

  minio:
    image: minio/minio
    ports:
        - "9999:9000"
    env_file: .env
    volumes:
        - ./data/videos_store:/export
    command: minio server /export
    container_name: ${MINIO_CONTAINER}
    networks:
      backend:
        aliases: 
          - ${MINIO_CONTAINER}


  smtp:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:1025"
    container_name: ${SMTP_CONTAINER}
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    environment:
      - "MAILDEV_OUTGOING_USER=${SMTP_USER}"
      - "MAILDEV_OUTGOING_PASS=${SMTP_PASSWORD}"
      - "MAILDEV_OUTGOING_SECURE=false"
    networks: 
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
  search: 
    driver: bridge

